db:
  username: ${db.value:postgres}
  password: postgres
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost,127.0.0.1
  properties:
    first: 123
    second: 456
    third.value: Third
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3

spring.profiles.active: qa

logging:
  level:
    root: INFO
    com.yadev.spring.database.repository: INFO
    org.springframework.jdbc.core: TRACE
  file:
    name: yadev.log
    path: /
spring:
  mvc:
    format:
      date: iso #yyyy-MM-dd  #we are using WebConfiguration implements WebMvcConfigurer
    view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
      batch_size: 50
      fetch_size: 50
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    open-in-view: false #means that the transactions won't be open at controllers layer.
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 675970289473-e09s8l0poaa893l3emod7na44remakob.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: http://localhost:8080/login/oath2/code/google
            scope: openid,email,profile